/**
 * openspec-plus smoke-test suite — DESIGN.md "Repo packaging".
 *
 * Zero dependencies: node:test + node:assert/strict. Every scenario spawns
 * install.mjs as a child process against a throwaway fixture project under
 * os.tmpdir(); CODEX_HOME is ALWAYS redirected into the fixture so the real
 * ~/.codex is never touched.
 */

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { after, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import { OPENSPEC_PLUS_VERSION, parseWorkflowFile } from '../lib/install-core.mjs';
import {
  BACKLOG_CONCURRENCY_PROFILE_PATH,
  OWNER_SCOPED_PROFILE,
  inspectBacklogConcurrencyProfile,
} from '../lib/backlog-concurrency.mjs';

// ---------------------------------------------------------------------------
// Contract constants — deliberately hardcoded (except the version) so the
// tests pin DESIGN.md rather than echoing the implementation.
// ---------------------------------------------------------------------------

const installPath = fileURLToPath(new URL('../install.mjs', import.meta.url));
const repoRoot = path.dirname(installPath);

const GENERATED_LINE = `<!-- generated by openspec-plus@${OPENSPEC_PLUS_VERSION}; re-run install.mjs to refresh -->`;
const POINTER_GUARD = '<!-- openspec-plus:pointer -->';
const AGENTS_START = '<!-- openspec-plus:start -->';
const AGENTS_END = '<!-- openspec-plus:end -->';
const DEPTH_GUARD = '<!-- openspec-plus:depth -->';
const RULE_PREFIX = '[openspec-plus:pillars]';
const DEPTH_LINE = '**Depth:** Minimal | Optimized | Production — <one-sentence boundary>';
const LEDGER_DEPTH_HEADER = '| Item | Depth | Depends on | Pointer / state |';

const ctxStart = (moduleName) => `>>> openspec-plus:${moduleName} >>>`;
const ctxEnd = (moduleName) => `<<< openspec-plus:${moduleName} <<<`;

const BACKLOG_IDS = ['backlog', 'brief', 'next'];
const PILLAR_IDS = ['pillar', 'definition'];
const ALL_IDS = [...BACKLOG_IDS, ...PILLAR_IDS];

/** Fixture config exercising the standard case: block-scalar context with
 * pre-existing content + a pre-existing rules.specs entry. */
const CONFIG_WITH_CONTEXT_AND_RULES = `# Project config
context: |
  Existing context line one.
  Existing context line two.
rules:
  specs:
    - "Existing spec rule."
`;

// Snapshot the real ~/.codex prompt files at suite start — the suite must
// never touch them (checked again in the CODEX_HOME scenario).
const realCodexPromptsDir = path.join(os.homedir(), '.codex', 'prompts');
const realCodexSnapshot = snapshotRealCodexPrompts();

function snapshotRealCodexPrompts() {
  const snap = {};
  for (const id of ALL_IDS) {
    const p = path.join(realCodexPromptsDir, `opsx-${id}.md`);
    snap[p] = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
  }
  return snap;
}

// ---------------------------------------------------------------------------
// Fixture + helpers
// ---------------------------------------------------------------------------

const fixtures = [];

after(() => {
  for (const dir of fixtures) fs.rmSync(dir, { recursive: true, force: true });
});

/** Per-scenario fixture: an empty project dir plus a dedicated CODEX_HOME. */
function makeFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'osplus-'));
  fixtures.push(root);
  const project = path.join(root, 'project');
  const codexHome = path.join(root, 'codex-home');
  fs.mkdirSync(project, { recursive: true });
  fs.mkdirSync(codexHome, { recursive: true });
  return { root, project, codexHome };
}

/** Spawns install.mjs; works from any cwd; CODEX_HOME always redirected. */
function runInstall(fx, args) {
  return execFileSync(process.execPath, [installPath, ...args, '--target', fx.project], {
    encoding: 'utf8',
    env: { ...process.env, CODEX_HOME: fx.codexHome },
  });
}

function writeConfig(fx, content) {
  fs.mkdirSync(path.join(fx.project, 'openspec'), { recursive: true });
  fs.writeFileSync(path.join(fx.project, 'openspec', 'config.yaml'), content);
}

function writeConcurrencyProfile(fx, value, { raw = false } = {}) {
  const profilePath = path.join(fx.project, BACKLOG_CONCURRENCY_PROFILE_PATH);
  fs.mkdirSync(path.dirname(profilePath), { recursive: true });
  fs.writeFileSync(profilePath, raw ? value : `${JSON.stringify(value, null, 2)}\n`);
}

const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');
const exists = (...parts) => fs.existsSync(path.join(...parts));

/** Recursive sorted list of file paths relative to dir (empty dirs omitted). */
function walk(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p, base));
    else out.push(path.relative(base, p));
  }
  return out;
}

/** Map of relative path -> file content for a whole tree. */
function snapshotTree(dir) {
  const map = {};
  for (const rel of walk(dir)) map[rel] = read(dir, rel);
  return map;
}

function countOccurrences(haystack, needle) {
  let count = 0;
  let idx = 0;
  while ((idx = haystack.indexOf(needle, idx)) !== -1) {
    count += 1;
    idx += needle.length;
  }
  return count;
}

function assertCount(haystack, needle, expected, label) {
  assert.equal(countOccurrences(haystack, needle), expected, `expected ${expected}× ${label ?? needle}`);
}

/** Reads a workflow body (everything after the frontmatter) from the repo. */
function workflowBody(moduleName, id) {
  const raw = read(repoRoot, 'modules', moduleName, 'workflows', `${id}.md`);
  const lines = raw.split('\n');
  assert.equal(lines[0].trim(), '---', `${moduleName}/${id}: frontmatter must open on line 1`);
  const close = lines.findIndex((l, i) => i > 0 && l.trim() === '---');
  assert.notEqual(close, -1, `${moduleName}/${id}: frontmatter never closed`);
  return lines
    .slice(close + 1)
    .join('\n')
    .replace(/^\n+/, '')
    .trimEnd();
}

// ---------------------------------------------------------------------------
// 1. dry-run writes nothing
// ---------------------------------------------------------------------------

describe('dry-run', () => {
  it('writes nothing to the project or CODEX_HOME', () => {
    const fx = makeFixture();
    fs.writeFileSync(path.join(fx.project, 'CLAUDE.md'), '# My Project\n\nSome notes.\n');
    writeConfig(fx, CONFIG_WITH_CONTEXT_AND_RULES);
    const before = snapshotTree(fx.project);

    const stdout = runInstall(fx, ['all', '--dry-run']);

    assert.match(stdout, /\[dry-run\] would write/);
    assert.deepEqual(snapshotTree(fx.project), before, 'project tree changed during --dry-run');
    assert.deepEqual(walk(fx.codexHome), [], 'CODEX_HOME gained files during --dry-run');
  });
});

// ---------------------------------------------------------------------------
// 2. backlog-only install
// ---------------------------------------------------------------------------

describe('backlog-only install', () => {
  const fx = makeFixture();
  fs.writeFileSync(path.join(fx.project, 'CLAUDE.md'), '# My Project\n\nSome notes.\n');
  writeConfig(fx, CONFIG_WITH_CONTEXT_AND_RULES);
  runInstall(fx, ['backlog']);

  it('writes command and skill files at the DESIGN paths for every tool', () => {
    for (const id of BACKLOG_IDS) {
      assert.ok(exists(fx.project, '.claude', 'commands', 'opsx', `${id}.md`), `.claude command ${id}`);
      assert.ok(exists(fx.project, '.cursor', 'commands', `opsx-${id}.md`), `.cursor command ${id}`);
      assert.ok(exists(fx.codexHome, 'prompts', `opsx-${id}.md`), `codex prompt ${id}`);
      for (const tool of ['.claude', '.codex', '.cursor']) {
        assert.ok(
          exists(fx.project, tool, 'skills', `openspec-plus-${id}`, 'SKILL.md'),
          `${tool} skill ${id}`
        );
      }
    }
    // Pillars commands were not requested and must not appear.
    for (const id of PILLAR_IDS) {
      assert.ok(!exists(fx.project, '.claude', 'commands', 'opsx', `${id}.md`), `unexpected ${id}`);
      assert.ok(!exists(fx.codexHome, 'prompts', `opsx-${id}.md`), `unexpected codex prompt ${id}`);
    }
  });

  it('renders Claude command frontmatter, generated-by line, and body', () => {
    const text = read(fx.project, '.claude', 'commands', 'opsx', 'backlog.md');
    assert.ok(text.startsWith('---\n'), 'frontmatter opens the file');
    assert.ok(text.includes('name: "OPSX+: Backlog"'), 'name field');
    assert.match(text, /^description: /m);
    assert.ok(text.includes('allowed-tools: Bash(openspec:*)'), 'allowed-tools field');
    assert.ok(text.includes('category: Workflow'), 'category field');
    assert.ok(text.includes('tags: [workflow, backlog]'), 'tags field');
    assert.ok(text.includes(`${GENERATED_LINE}\n\n`), 'generated-by line after frontmatter');
    const body = workflowBody('openspec-backlog', 'backlog');
    assert.ok(text.endsWith(`\n\n${body}\n`), 'file ends with the workflow body');
  });

  it('renders Cursor command frontmatter', () => {
    const text = read(fx.project, '.cursor', 'commands', 'opsx-backlog.md');
    assert.ok(text.includes('name: /opsx-backlog'), 'name field');
    assert.ok(text.includes('id: opsx-backlog'), 'id field');
    assert.ok(text.includes('category: Workflow'), 'category field');
    assert.match(text, /^description: /m);
    assert.ok(text.includes(GENERATED_LINE), 'generated-by line');
  });

  it('renders Codex prompt frontmatter into CODEX_HOME', () => {
    const text = read(fx.codexHome, 'prompts', 'opsx-backlog.md');
    assert.match(text, /^description: /m);
    assert.match(text, /^argument-hint: /m);
    assert.ok(
      text.includes('free-form context, goals, or research to capture'),
      'argument hint text'
    );
    assert.ok(text.includes(GENERATED_LINE), 'generated-by line');
  });

  it('renders skill frontmatter per the DESIGN table', () => {
    for (const tool of ['.claude', '.codex', '.cursor']) {
      const text = read(fx.project, tool, 'skills', 'openspec-plus-backlog', 'SKILL.md');
      assert.ok(text.includes('name: openspec-plus-backlog'), `${tool}: name field`);
      assert.ok(text.includes('allowed-tools: Bash(openspec:*)'), `${tool}: allowed-tools`);
      assert.ok(text.includes('license: MIT'), `${tool}: license`);
      assert.ok(
        text.includes(
          'compatibility: Requires the openspec CLI and the openspec-plus openspec-backlog module.'
        ),
        `${tool}: compatibility`
      );
      assert.ok(text.includes('author: openspec-plus'), `${tool}: metadata.author`);
      assert.match(text, /^ {2}version: "\d+\.\d+\.\d+"$/m, `${tool}: metadata.version`);
      assert.ok(
        text.includes(`generatedBy: "openspec-plus@${OPENSPEC_PLUS_VERSION}"`),
        `${tool}: metadata.generatedBy`
      );
      assert.ok(text.includes(GENERATED_LINE), `${tool}: generated-by line`);
    }
  });

  it('copies the scaffold and the ledger has NO Depth column', () => {
    for (const rel of ['README.md', 'AGENTS.md', 'backlog.md', 'templates/brief.md']) {
      assert.ok(exists(fx.project, 'openspec', 'backlog', rel), `scaffold file ${rel}`);
    }
    assert.ok(exists(fx.project, 'openspec', 'backlog', 'briefs', '.gitkeep'), 'briefs/.gitkeep');
    assert.ok(exists(fx.project, 'openspec', 'backlog', 'archive', '.gitkeep'), 'archive/.gitkeep');
    const ledger = read(fx.project, 'openspec', 'backlog', 'backlog.md');
    assert.ok(!/\|\s*Depth\s*\|/.test(ledger), 'ledger must not have a Depth column yet');
    assert.ok(ledger.includes('| Item | Depends on | Pointer / state |'), 'base ledger header');
    // Pillars scaffold must not appear.
    assert.ok(!exists(fx.project, 'openspec', 'pillars'), 'openspec/pillars must not exist');
  });

  it('appends the marker-guarded context block, preserving pre-existing config', () => {
    const config = read(fx.project, 'openspec', 'config.yaml');
    assert.ok(config.includes('Existing context line one.'), 'pre-existing context survives');
    assert.ok(config.includes('Existing context line two.'), 'pre-existing context survives');
    assert.ok(config.includes('- "Existing spec rule."'), 'pre-existing rules.specs entry survives');
    assertCount(config, ctxStart('openspec-backlog'), 1, 'backlog context start marker');
    assertCount(config, ctxEnd('openspec-backlog'), 1, 'backlog context end marker');
    assert.ok(!config.includes(RULE_PREFIX), 'backlog install must not inject pillar rules');

    // The marker block lives INSIDE the context block scalar: indented, after
    // the pre-existing content, before the rules mapping.
    const lines = config.split('\n');
    const startLine = lines.find((l) => l.includes(ctxStart('openspec-backlog')));
    assert.match(startLine, /^\s+>>>/, 'marker line is indented block-scalar content');
    const idxExisting = config.indexOf('Existing context line two.');
    const idxStart = config.indexOf(ctxStart('openspec-backlog'));
    const idxEnd = config.indexOf(ctxEnd('openspec-backlog'));
    const idxRules = config.indexOf('\nrules:');
    assert.ok(idxExisting < idxStart && idxStart < idxEnd && idxEnd < idxRules,
      'context block ordering: existing content, then marker block, then rules:');
  });

  it('writes AGENTS.md with the order model only', () => {
    const agents = read(fx.project, 'AGENTS.md');
    assertCount(agents, AGENTS_START, 1, 'AGENTS start marker');
    assertCount(agents, AGENTS_END, 1, 'AGENTS end marker');
    assert.ok(agents.includes('**Order model.**'), 'order model paragraph');
    assert.ok(!agents.includes('**Authority model.**'), 'no authority model without pillars');
    for (const id of BACKLOG_IDS) {
      assert.ok(agents.includes(`| \`/opsx:${id}\` |`), `command table row for ${id}`);
    }
    for (const id of PILLAR_IDS) {
      assert.ok(!agents.includes(`| \`/opsx:${id}\` |`), `no command table row for ${id}`);
    }
  });

  it('prepends the pointer to the existing CLAUDE.md and skips absent CODEX.md', () => {
    const claude = read(fx.project, 'CLAUDE.md');
    assert.ok(claude.startsWith(`${POINTER_GUARD}\n`), 'pointer guard leads the file');
    assert.ok(claude.includes('[AGENTS.md](AGENTS.md)'), 'pointer links AGENTS.md');
    assert.ok(claude.includes('# My Project'), 'original content preserved');
    assert.ok(claude.includes('Some notes.'), 'original content preserved');
    assert.ok(!exists(fx.project, 'CODEX.md'), 'CODEX.md must not be created');
  });
});

// ---------------------------------------------------------------------------
// 2a. repository-owned concurrency profile
// ---------------------------------------------------------------------------

describe('backlog concurrency profile', () => {
  it('keeps a fresh minimal repository serial and scaffolds only the strict schema', () => {
    const fx = makeFixture();
    const stdout = runInstall(fx, ['backlog']);

    assert.match(stdout, /serial\s+.*concurrency\.json \(profile absent\)/);
    assert.ok(
      exists(
        fx.project,
        'openspec',
        'backlog',
        'templates',
        'concurrency-profile.schema.json'
      ),
      'strict profile schema was scaffolded'
    );
    assert.ok(
      !exists(fx.project, 'openspec', 'backlog', 'concurrency.json'),
      'installer must not opt a repository in'
    );
    assert.deepEqual(inspectBacklogConcurrencyProfile(fx.project).mode, 'serial');
  });

  it('accepts the exact profile without changing a HyperFactory-shaped ledger', () => {
    const fx = makeFixture();
    const backlogDir = path.join(fx.project, 'openspec', 'backlog');
    fs.mkdirSync(path.join(backlogDir, 'templates'), { recursive: true });
    const ledger = `# Backlog Ledger

## In flight

| Item | Product Area | Depth | Concurrency | Depends on | Pointer / state |
|---|---|---|---|---|---|

## Upcoming

| Item | Product Area | Depth | Concurrency | Depends on | Pointer / state |
|---|---|---|---|---|---|
| sample | Factory | Production | Parallel-safe | — | — |
`;
    fs.writeFileSync(path.join(backlogDir, 'backlog.md'), ledger);
    fs.writeFileSync(path.join(backlogDir, 'product-areas.md'), '# Product Areas\n\n- Factory\n');
    fs.writeFileSync(path.join(backlogDir, 'templates', 'brief.md'), '# Repository brief\n');
    writeConcurrencyProfile(fx, OWNER_SCOPED_PROFILE);

    const stdout = runInstall(fx, ['backlog']);

    assert.match(stdout, /accepted\s+.*concurrency\.json \(owner-scoped-v1, implementation WIP limit 2\)/);
    assert.equal(read(backlogDir, 'backlog.md'), ledger, 'six-column ledger changed');
    assert.equal(inspectBacklogConcurrencyProfile(fx.project).status, 'enabled');

    const projections = [
      read(fx.project, '.claude', 'commands', 'opsx', 'next.md'),
      read(fx.project, '.claude', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.project, '.codex', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.project, '.cursor', 'commands', 'opsx-next.md'),
      read(fx.project, '.cursor', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.codexHome, 'prompts', 'opsx-next.md'),
    ];
    for (const text of projections) {
      assert.ok(text.includes('owner-scoped-v1'), 'projection lacks exact live-profile contract');
      assert.ok(text.includes('Product Area') || text.includes('one-item end-to-end'),
        'projection lacks repository-aware or serialized lifecycle guidance');
    }

    const projectAfterFirstInstall = snapshotTree(fx.project);
    const codexAfterFirstInstall = snapshotTree(fx.codexHome);
    runInstall(fx, ['backlog']);
    assert.deepEqual(
      snapshotTree(fx.project),
      projectAfterFirstInstall,
      'valid-profile project changed on reinstall'
    );
    assert.deepEqual(
      snapshotTree(fx.codexHome),
      codexAfterFirstInstall,
      'valid-profile CODEX_HOME changed on reinstall'
    );
  });

  it('reports malformed JSON and leaves universal guidance fail-closed', () => {
    const fx = makeFixture();
    writeConcurrencyProfile(fx, '{"schemaVersion":', { raw: true });

    const stdout = runInstall(fx, ['backlog']);

    assert.match(stdout, /MANUAL\s+Rejected .*concurrency\.json/);
    assert.match(stdout, /malformed JSON/);
    assert.equal(inspectBacklogConcurrencyProfile(fx.project).mode, 'serial');
    assert.ok(
      read(fx.project, '.claude', 'commands', 'opsx', 'next.md').includes(
        'Missing, unreadable,\n   malformed'
      ),
      'fail-closed next guidance was not regenerated'
    );
  });

  it('reports unsupported values and additional keys as serial', () => {
    const fx = makeFixture();
    writeConcurrencyProfile(fx, {
      ...OWNER_SCOPED_PROFILE,
      implementationWipLimit: 3,
      retainedGrant: true,
    });

    const stdout = runInstall(fx, ['backlog']);
    const result = inspectBacklogConcurrencyProfile(fx.project);

    assert.match(stdout, /MANUAL\s+Rejected .*concurrency\.json/);
    assert.equal(result.status, 'unsupported');
    assert.equal(result.mode, 'serial');
    assert.ok(result.diagnostics.some((line) => line.includes('unknown keys: retainedGrant')));
    assert.ok(result.diagnostics.some((line) => line.includes('implementationWipLimit must equal 2')));
  });

  it('revocation immediately returns to serial without stale generated authorization', () => {
    const fx = makeFixture();
    writeConcurrencyProfile(fx, OWNER_SCOPED_PROFILE);
    runInstall(fx, ['backlog']);
    const generatedBefore = read(fx.project, '.claude', 'commands', 'opsx', 'next.md');

    fs.unlinkSync(path.join(fx.project, BACKLOG_CONCURRENCY_PROFILE_PATH));
    const stdout = runInstall(fx, ['backlog']);

    assert.match(stdout, /serial\s+.*concurrency\.json \(profile absent\)/);
    assert.equal(inspectBacklogConcurrencyProfile(fx.project).mode, 'serial');
    assert.equal(
      read(fx.project, '.claude', 'commands', 'opsx', 'next.md'),
      generatedBefore,
      'generated guidance encoded a stale enabled/disabled variant'
    );
  });
});

describe('owner-scoped eligibility guidance', () => {
  it('pins every denial and serialization rule across next projections', () => {
    const fx = makeFixture();
    writeConcurrencyProfile(fx, OWNER_SCOPED_PROFILE);
    runInstall(fx, ['backlog']);
    const projections = [
      read(fx.project, '.claude', 'commands', 'opsx', 'next.md'),
      read(fx.project, '.claude', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.project, '.codex', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.project, '.cursor', 'commands', 'opsx-next.md'),
      read(fx.project, '.cursor', 'skills', 'openspec-plus-next', 'SKILL.md'),
      read(fx.codexHome, 'prompts', 'opsx-next.md'),
    ];
    const cases = [
      ['independent scopes may overlap', /Satisfying every condition permits overlap/],
      ['same Owner Scope', /Same Owner Scope/],
      ['same Engineer', /same Engineer/],
      ['dependency only proposed', /proposed-only dependency/],
      ['third lane', /third lane/],
      ['stale capacity', /stale capacity/],
      ['serialized surface', /serialized-surface collision denies admission/],
      ['racing admission', /concurrent empty-argument `\/opsx:next` selection/],
    ];

    for (const text of projections) {
      for (const [name, pattern] of cases) {
        assert.match(text, pattern, `${name} denial missing from generated projection`);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// 3. pillars on top of backlog
// ---------------------------------------------------------------------------

describe('pillars installed on top of backlog', () => {
  const fx = makeFixture();
  writeConfig(fx, CONFIG_WITH_CONTEXT_AND_RULES);
  runInstall(fx, ['backlog']);
  runInstall(fx, ['pillars']);

  it('merges prefixed rules into config.yaml, preserving pre-existing entries', () => {
    const config = read(fx.project, 'openspec', 'config.yaml');
    assertCount(config, RULE_PREFIX, 2, 'prefixed rules (proposal + specs)');
    assertCount(config, 'Declare exactly one delivery depth', 1, 'proposal rule');
    assertCount(config, 'Cite at least one pillar', 1, 'specs rule');
    assert.ok(config.includes('- "Existing spec rule."'), 'pre-existing specs rule survives');
    assert.match(config, /^ {2}proposal:$/m, 'proposal artifact key added under rules:');
    // The injected specs rule sits inside the existing specs entry.
    const lines = config.split('\n');
    const specsIdx = lines.findIndex((l) => /^ {2}specs:/.test(l));
    const existingIdx = lines.findIndex((l) => l.includes('Existing spec rule.'));
    const injectedIdx = lines.findIndex((l) => l.includes('Cite at least one pillar'));
    assert.ok(specsIdx !== -1 && specsIdx < existingIdx && existingIdx < injectedIdx,
      'injected specs rule appended after the pre-existing one');
    assert.match(lines[injectedIdx], /^\s+- "/, 'injected rule is a quoted list item');
  });

  it('keeps both context marker blocks and the pre-existing context', () => {
    const config = read(fx.project, 'openspec', 'config.yaml');
    assert.ok(config.includes('Existing context line one.'), 'pre-existing context survives');
    assertCount(config, ctxStart('openspec-backlog'), 1, 'backlog context start marker');
    assertCount(config, ctxStart('openspec-pillars'), 1, 'pillars context start marker');
    assertCount(config, ctxEnd('openspec-pillars'), 1, 'pillars context end marker');
  });

  it('AGENTS.md gains the authority model and keeps the order model', () => {
    const agents = read(fx.project, 'AGENTS.md');
    assert.ok(agents.includes('**Authority model.**'), 'authority model paragraph');
    assert.ok(agents.includes('**Order model.**'), 'order model paragraph');
    for (const id of ALL_IDS) {
      assert.ok(agents.includes(`| \`/opsx:${id}\` |`), `command table row for ${id}`);
    }
  });

  it('depth hook: inserts the Depth column into every ledger table', () => {
    const ledger = read(fx.project, 'openspec', 'backlog', 'backlog.md');
    assertCount(ledger, LEDGER_DEPTH_HEADER, 2, 'Depth header (In flight + Upcoming)');
    assertCount(ledger, '|---|---|---|---|', 2, 'four-cell divider rows');
    assert.ok(!ledger.includes('| Item | Depends on |'), 'no depth-less header remains');
  });

  it('depth hook: adds the Depth line to the brief template after Depends on', () => {
    const template = read(fx.project, 'openspec', 'backlog', 'templates', 'brief.md');
    assertCount(template, DEPTH_LINE, 1, 'Depth template line');
    const lines = template.split('\n');
    const dependsIdx = lines.findIndex((l) => l.startsWith('**Depends on:**'));
    assert.notEqual(dependsIdx, -1, 'Depends on line present');
    assert.equal(lines[dependsIdx + 1], DEPTH_LINE, 'Depth line directly after Depends on');
    assert.ok(
      template.includes('## Intended outcome'),
      'Intended outcome section coexists with the injected Depth line'
    );
  });

  it('depth hook: appends marker-guarded cross-notes to both READMEs', () => {
    const backlogReadme = read(fx.project, 'openspec', 'backlog', 'README.md');
    const pillarsReadme = read(fx.project, 'openspec', 'pillars', 'README.md');
    assertCount(backlogReadme, DEPTH_GUARD, 1, 'depth guard in backlog README');
    assert.ok(
      backlogReadme.includes('## Depth column (openspec-pillars integration)'),
      'backlog README cross-note'
    );
    assertCount(pillarsReadme, DEPTH_GUARD, 1, 'depth guard in pillars README');
    assert.ok(
      pillarsReadme.includes('## Backlog projection (openspec-backlog integration)'),
      'pillars README cross-note'
    );
  });
});

// ---------------------------------------------------------------------------
// 4. reverse install order equivalence
// ---------------------------------------------------------------------------

describe('reverse install order equivalence', () => {
  it('backlog→pillars and pillars→backlog converge to the same state', () => {
    const fxA = makeFixture();
    runInstall(fxA, ['backlog']);
    runInstall(fxA, ['pillars']);

    const fxB = makeFixture();
    runInstall(fxB, ['pillars']);
    runInstall(fxB, ['backlog']);

    const filesA = walk(fxA.project);
    const filesB = walk(fxB.project);
    assert.deepEqual(filesA, filesB, 'both orders produce the same file set');

    const configRel = path.join('openspec', 'config.yaml');
    for (const rel of filesA) {
      if (rel === configRel) continue; // marker-block order differs; checked semantically below
      assert.equal(read(fxA.project, rel), read(fxB.project, rel), `content differs: ${rel}`);
    }

    for (const fx of [fxA, fxB]) {
      const config = read(fx.project, configRel);
      assertCount(config, ctxStart('openspec-backlog'), 1, 'backlog context marker');
      assertCount(config, ctxStart('openspec-pillars'), 1, 'pillars context marker');
      assertCount(config, RULE_PREFIX, 2, 'prefixed rules');
    }

    // Codex prompts (global, redirected per fixture) must match too.
    assert.deepEqual(snapshotTree(fxA.codexHome), snapshotTree(fxB.codexHome),
      'CODEX_HOME trees differ between install orders');
  });
});

// ---------------------------------------------------------------------------
// 5. full idempotency re-run
// ---------------------------------------------------------------------------

describe('idempotent re-run', () => {
  const fx = makeFixture();
  fs.writeFileSync(path.join(fx.project, 'CLAUDE.md'), '# My Project\n');
  writeConfig(fx, CONFIG_WITH_CONTEXT_AND_RULES);
  runInstall(fx, ['all']);
  const firstProject = snapshotTree(fx.project);
  const firstCodex = snapshotTree(fx.codexHome);
  runInstall(fx, ['all']);

  it('second run changes nothing on disk', () => {
    assert.deepEqual(snapshotTree(fx.project), firstProject, 'project tree changed on re-run');
    assert.deepEqual(snapshotTree(fx.codexHome), firstCodex, 'CODEX_HOME changed on re-run');
  });

  it('markers, rules, columns, and pointers appear exactly once', () => {
    const config = read(fx.project, 'openspec', 'config.yaml');
    for (const moduleName of ['openspec-backlog', 'openspec-pillars']) {
      assertCount(config, ctxStart(moduleName), 1, `${moduleName} context start marker`);
      assertCount(config, ctxEnd(moduleName), 1, `${moduleName} context end marker`);
    }
    assertCount(config, 'Declare exactly one delivery depth', 1, 'proposal rule');
    assertCount(config, 'Cite at least one pillar', 1, 'specs rule');
    assertCount(config, '- "Existing spec rule."', 1, 'pre-existing rule');

    const claude = read(fx.project, 'CLAUDE.md');
    assertCount(claude, POINTER_GUARD, 1, 'CLAUDE.md pointer guard');

    const agents = read(fx.project, 'AGENTS.md');
    assertCount(agents, AGENTS_START, 1, 'AGENTS start marker');
    assertCount(agents, AGENTS_END, 1, 'AGENTS end marker');
    assertCount(agents, '**Order model.**', 1, 'order model paragraph');
    assertCount(agents, '**Authority model.**', 1, 'authority model paragraph');

    const ledger = read(fx.project, 'openspec', 'backlog', 'backlog.md');
    assertCount(ledger, LEDGER_DEPTH_HEADER, 2, 'Depth headers (one per table)');
    assertCount(ledger, 'Depth', 2, 'Depth appears once per table header only');

    const template = read(fx.project, 'openspec', 'backlog', 'templates', 'brief.md');
    assertCount(template, '**Depth:**', 1, 'brief template Depth line');

    assertCount(read(fx.project, 'openspec', 'backlog', 'README.md'), DEPTH_GUARD, 1,
      'backlog README depth guard');
    assertCount(read(fx.project, 'openspec', 'pillars', 'README.md'), DEPTH_GUARD, 1,
      'pillars README depth guard');
  });
});

// ---------------------------------------------------------------------------
// 6. tool filtering
// ---------------------------------------------------------------------------

describe('tool filtering (--tools claude)', () => {
  const fx = makeFixture();
  runInstall(fx, ['all', '--tools', 'claude']);

  it('writes Claude files only', () => {
    for (const id of ALL_IDS) {
      assert.ok(exists(fx.project, '.claude', 'commands', 'opsx', `${id}.md`), `.claude command ${id}`);
      assert.ok(
        exists(fx.project, '.claude', 'skills', `openspec-plus-${id}`, 'SKILL.md'),
        `.claude skill ${id}`
      );
    }
    assert.ok(!exists(fx.project, '.cursor'), '.cursor must not be created');
    assert.ok(!exists(fx.project, '.codex'), '.codex must not be created');
    assert.deepEqual(walk(fx.codexHome), [], 'no Codex prompts written');
  });

  it('still copies scaffolds and wires config', () => {
    assert.ok(exists(fx.project, 'openspec', 'backlog', 'backlog.md'), 'backlog scaffold');
    assert.ok(exists(fx.project, 'openspec', 'pillars', 'DEFINITIONS.md'), 'pillars scaffold');
    const config = read(fx.project, 'openspec', 'config.yaml');
    assertCount(config, ctxStart('openspec-backlog'), 1, 'backlog context marker');
    assertCount(config, RULE_PREFIX, 2, 'prefixed rules');
  });
});

describe('existing shared agents skill convention', () => {
  it('refreshes .agents/skills without recreating .codex/skills', () => {
    const fx = makeFixture();
    fs.mkdirSync(path.join(fx.project, '.agents', 'skills'), { recursive: true });

    runInstall(fx, ['backlog']);

    for (const id of BACKLOG_IDS) {
      const skillPath = path.join(
        fx.project,
        '.agents',
        'skills',
        `openspec-plus-${id}`,
        'SKILL.md'
      );
      assert.ok(fs.existsSync(skillPath), `.agents skill ${id}`);
      assert.ok(read(skillPath).includes(GENERATED_LINE), `.agents skill ${id} is generated`);
      assert.ok(
        !exists(fx.project, '.codex', 'skills', `openspec-plus-${id}`, 'SKILL.md'),
        `.codex duplicate ${id} must not be created`
      );
    }
  });

  it('keeps the standard .codex/skills target when both roots already exist', () => {
    const fx = makeFixture();
    fs.mkdirSync(path.join(fx.project, '.agents', 'skills'), { recursive: true });
    fs.mkdirSync(path.join(fx.project, '.codex', 'skills'), { recursive: true });

    runInstall(fx, ['backlog']);

    assert.ok(
      exists(fx.project, '.codex', 'skills', 'openspec-plus-next', 'SKILL.md'),
      'standard Codex skill was not generated'
    );
    assert.ok(
      !exists(fx.project, '.agents', 'skills', 'openspec-plus-next', 'SKILL.md'),
      'ambiguous repository was silently redirected'
    );
  });
});

// ---------------------------------------------------------------------------
// 7. config edge cases
// ---------------------------------------------------------------------------

describe('config.yaml edge cases', () => {
  it('plain-scalar context: manual bail-out, file unchanged, exit code 0', () => {
    const fx = makeFixture();
    const original = 'context: a plain scalar value\n';
    writeConfig(fx, original);
    const stdout = runInstall(fx, ['backlog']); // execFileSync throws on non-zero exit
    assert.ok(stdout.includes('MANUAL'), 'a manual step is reported');
    assert.ok(stdout.includes('Manual steps required:'), 'summary lists the manual step');
    assert.ok(stdout.includes(ctxStart('openspec-backlog')), 'manual snippet includes the marker block');
    assert.equal(read(fx.project, 'openspec', 'config.yaml'), original, 'config.yaml untouched');
  });

  it('rules: with a trailing comment still merges', () => {
    const fx = makeFixture();
    writeConfig(
      fx,
      `context: |
  Existing context.
rules: # keep these tidy
  specs:
    - "Existing spec rule."
`
    );
    const stdout = runInstall(fx, ['pillars']);
    assert.ok(!stdout.includes('MANUAL'), 'no manual bail-out');
    const config = read(fx.project, 'openspec', 'config.yaml');
    assert.ok(config.includes('rules: # keep these tidy'), 'comment preserved');
    assertCount(config, RULE_PREFIX, 2, 'prefixed rules merged');
    assert.ok(config.includes('- "Existing spec rule."'), 'pre-existing rule survives');
    assert.match(config, /^ {2}proposal:$/m, 'proposal key added');
  });

  it('file without a trailing newline ends with a newline after surgery', () => {
    const fx = makeFixture();
    writeConfig(
      fx,
      'context: |\n  Existing context.\nrules:\n  specs:\n    - "Existing spec rule."' // no \n
    );
    runInstall(fx, ['all']);
    const config = read(fx.project, 'openspec', 'config.yaml');
    assert.ok(config.endsWith('\n'), 'result ends with a newline');
    assert.ok(config.includes('Existing context.'), 'pre-existing context survives');
    assertCount(config, ctxStart('openspec-backlog'), 1, 'backlog context marker');
    assertCount(config, ctxStart('openspec-pillars'), 1, 'pillars context marker');
    assertCount(config, RULE_PREFIX, 2, 'prefixed rules merged');
  });
});

// ---------------------------------------------------------------------------
// 8. CODEX_HOME redirection
// ---------------------------------------------------------------------------

describe('CODEX_HOME redirection', () => {
  it('writes prompts under the fixture CODEX_HOME, never under ~/.codex', () => {
    const fx = makeFixture();
    runInstall(fx, ['all']);
    for (const id of ALL_IDS) {
      const promptPath = path.join(fx.codexHome, 'prompts', `opsx-${id}.md`);
      assert.ok(fs.existsSync(promptPath), `prompt for ${id} under fixture CODEX_HOME`);
      assert.ok(read(promptPath).includes(GENERATED_LINE), `prompt for ${id} is generated`);
    }
    // The real ~/.codex prompts are byte-identical to the suite-start snapshot
    // (and still absent if they were absent).
    for (const [realPath, before] of Object.entries(realCodexSnapshot)) {
      const now = fs.existsSync(realPath) ? fs.readFileSync(realPath, 'utf8') : null;
      assert.equal(now, before, `real Codex prompt was touched: ${realPath}`);
    }
  });
});

// ---------------------------------------------------------------------------
// 9. prose budgets (DESIGN "config snippets")
// ---------------------------------------------------------------------------

describe('prose budgets', () => {
  it('backlog context snippet is at most 15 lines', () => {
    const text = read(repoRoot, 'modules', 'openspec-backlog', 'config-snippets', 'context.md');
    const lines = text.replace(/\s+$/, '').split('\n');
    assert.ok(lines.length <= 15, `backlog context.md is ${lines.length} lines (max 15)`);
  });

  it('pillars context snippet is at most 8 lines', () => {
    const text = read(repoRoot, 'modules', 'openspec-pillars', 'config-snippets', 'context.md');
    const lines = text.replace(/\s+$/, '').split('\n');
    assert.ok(lines.length <= 8, `pillars context.md is ${lines.length} lines (max 8)`);
  });
});

// ---------------------------------------------------------------------------
// 10. scaffold invariants
// ---------------------------------------------------------------------------

describe('scaffold invariants', () => {
  const backlogScaffold = path.join(repoRoot, 'modules', 'openspec-backlog', 'scaffold', 'backlog');

  it('templates/brief.md exists in the scaffold source', () => {
    assert.ok(exists(backlogScaffold, 'templates', 'brief.md'), 'templates/brief.md missing');
  });

  it('brief template carries the ## Intended outcome section', () => {
    const template = read(backlogScaffold, 'templates', 'brief.md');
    assert.ok(
      template.includes('## Intended outcome'),
      'brief template missing the ## Intended outcome section'
    );
  });

  it('templates/worklog.md exists and carries the State/Entries structure', () => {
    const worklogPath = path.join(backlogScaffold, 'templates', 'worklog.md');
    assert.ok(fs.existsSync(worklogPath), 'templates/worklog.md missing from scaffold source');
    const text = fs.readFileSync(worklogPath, 'utf8');
    assert.ok(text.includes('## State'), 'worklog template has a ## State section');
    assert.ok(text.includes('## Entries'), 'worklog template has an ## Entries section');
  });

  it('ships the strict owner-scoped concurrency schema without enabling a profile', () => {
    const schema = JSON.parse(
      read(backlogScaffold, 'templates', 'concurrency-profile.schema.json')
    );
    assert.equal(schema.additionalProperties, false);
    assert.deepEqual(schema.required.sort(), Object.keys(OWNER_SCOPED_PROFILE).sort());
    assert.equal(schema.properties.schemaVersion.const, 1);
    assert.equal(schema.properties.profile.const, 'owner-scoped-v1');
    assert.equal(schema.properties.implementationWipLimit.const, 2);
    assert.ok(
      !exists(backlogScaffold, 'concurrency.json'),
      'fresh scaffold must remain serial by omitting concurrency.json'
    );
  });

  it('base scaffold ledger has no Depth column', () => {
    const ledger = read(backlogScaffold, 'backlog.md');
    assert.ok(!/\|\s*Depth\s*\|/.test(ledger), 'scaffold ledger must not carry a Depth column');
    assertCount(ledger, '| Item | Depends on | Pointer / state |', 2, 'base three-column headers');
  });
});

// ---------------------------------------------------------------------------
// CRLF tolerance — Windows checkouts (autocrlf) and CRLF user projects
// ---------------------------------------------------------------------------

describe('CRLF tolerance', () => {
  it('parseWorkflowFile accepts CRLF line endings', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'osplus-crlf-'));
    fixtures.push(dir);
    const p = path.join(dir, 'wf.md');
    fs.writeFileSync(p, '---\r\nid: sample\r\ndescription: CRLF sample\r\n---\r\nBody line.\r\n');
    const { attrs, body } = parseWorkflowFile(p);
    assert.equal(attrs.id, 'sample');
    assert.equal(attrs.description, 'CRLF sample');
    assert.ok(body.includes('Body line.'), 'body parsed');
  });

  it('config surgery tolerates a CRLF config.yaml and writes back LF', () => {
    const fx = makeFixture();
    writeConfig(fx, CONFIG_WITH_CONTEXT_AND_RULES.replace(/\n/g, '\r\n'));
    runInstall(fx, ['backlog']);
    const config = read(fx.project, 'openspec', 'config.yaml');
    const count = (needle) => config.split(needle).length - 1;
    assert.equal(count(ctxStart('openspec-backlog')), 1, 'context start marker exactly once');
    assert.equal(count(ctxEnd('openspec-backlog')), 1, 'context end marker exactly once');
    assert.ok(config.includes('Existing context line one.'), 'pre-existing context survives');
    assert.ok(config.includes('- "Existing spec rule."'), 'pre-existing rule survives');
    assert.ok(!config.includes('\r'), 'result is fully LF-normalized');
    assert.ok(config.endsWith('\n'), 'trailing newline preserved');
  });
});
