/**
 * openspec-plus install core
 *
 * Shared helpers for install.mjs: module loading, workflow parsing, per-tool
 * file rendering, scaffold copying, marker-guarded config/AGENTS surgery, and
 * the pairwise integration-hook registry.
 *
 * Zero dependencies. Node >= 18. See DESIGN.md for the contract this
 * implements — paths, formats, and markers are all pinned there.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';

export const OPENSPEC_PLUS_VERSION = '0.1.0';

/** Header line placed after the frontmatter of every file the installer composes. */
export const GENERATED_BY_LINE = `<!-- generated by openspec-plus@${OPENSPEC_PLUS_VERSION}; re-run install.mjs to refresh -->`;

export const AGENTS_START_MARKER = '<!-- openspec-plus:start -->';
export const AGENTS_END_MARKER = '<!-- openspec-plus:end -->';
export const POINTER_GUARD = '<!-- openspec-plus:pointer -->';
export const DEPTH_NOTE_GUARD = '<!-- openspec-plus:depth -->';
export const PILLARS_RULE_PREFIX = '[openspec-plus:pillars]';

// ---------------------------------------------------------------------------
// Write summary + the single write/copy funnel
// ---------------------------------------------------------------------------

/**
 * Creates the writer every file-system mutation flows through. Respects
 * dry-run mode and collects the written / kept / skipped / manual-step
 * summary printed at the end of a run.
 */
export function createWriter({ dryRun = false } = {}) {
  const summary = { written: [], kept: [], skipped: [], manual: [] };

  /**
   * Writes a file (creating parent directories). With `guardGenerated`, an
   * existing file that does not carry the openspec-plus header is left
   * untouched — we only overwrite files we generated ourselves.
   */
  function write(filePath, content, { guardGenerated = false } = {}) {
    if (fs.existsSync(filePath)) {
      const existing = fs.readFileSync(filePath, 'utf8');
      if (existing === content) {
        keep(filePath, 'already up to date');
        return true;
      }
      if (guardGenerated && !existing.includes('generated by openspec-plus')) {
        skip(filePath, 'existing file was not generated by openspec-plus — left untouched');
        return false;
      }
    }
    if (dryRun) {
      // A real run composes sequential surgeries on the same file (e.g. three
      // config.yaml edits) into one write; report each planned file once.
      if (!summary.written.includes(filePath)) {
        console.log(`[dry-run] would write ${filePath}`);
        summary.written.push(filePath);
      }
      return true;
    }
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`  written  ${filePath}`);
    summary.written.push(filePath);
    return true;
  }

  /** Copies a file only if the destination does not exist (scaffold rule). */
  function copyKeepExisting(srcPath, destPath) {
    if (fs.existsSync(destPath)) {
      keep(destPath, 'kept existing');
      return false;
    }
    if (dryRun) {
      console.log(`[dry-run] would write ${destPath}`);
    } else {
      fs.mkdirSync(path.dirname(destPath), { recursive: true });
      fs.copyFileSync(srcPath, destPath);
      console.log(`  written  ${destPath}`);
    }
    summary.written.push(destPath);
    return true;
  }

  function keep(filePath, reason) {
    summary.kept.push({ path: filePath, reason });
    console.log(`  kept     ${filePath} (${reason})`);
  }

  function skip(filePath, reason) {
    summary.skipped.push({ path: filePath, reason });
    console.log(`  skipped  ${filePath} (${reason})`);
  }

  /** Records a step the user must do by hand (conservative bail-outs). */
  function manual(title, snippet = '') {
    summary.manual.push({ title, snippet });
    console.log(`  MANUAL   ${title}`);
  }

  function printSummary() {
    console.log('');
    console.log('Summary');
    console.log(`  written      : ${summary.written.length}${dryRun ? ' (dry-run — nothing touched)' : ''}`);
    console.log(`  kept existing: ${summary.kept.length}`);
    console.log(`  skipped      : ${summary.skipped.length}`);
    console.log(`  manual steps : ${summary.manual.length}`);
    if (summary.manual.length > 0) {
      console.log('');
      console.log('Manual steps required:');
      summary.manual.forEach((step, i) => {
        console.log(`  ${i + 1}. ${step.title}`);
        if (step.snippet) {
          for (const line of step.snippet.split('\n')) {
            console.log(`       ${line}`);
          }
        }
      });
    }
  }

  return { write, copyKeepExisting, keep, skip, manual, printSummary, summary, dryRun };
}

// ---------------------------------------------------------------------------
// Module loading
// ---------------------------------------------------------------------------

const REQUIRED_MODULE_FIELDS = ['name', 'version', 'description', 'commands', 'scaffold', 'detectFile'];

/**
 * Discovers modules from `<modulesDir>/<module>/module.json`. Returns the
 * parsed specs with a `dir` property pointing at the module folder.
 */
export function loadModules(modulesDir) {
  if (!fs.existsSync(modulesDir)) return [];
  const modules = [];
  const entries = fs
    .readdirSync(modulesDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const jsonPath = path.join(modulesDir, entry.name, 'module.json');
    if (!fs.existsSync(jsonPath)) continue;
    let spec;
    try {
      spec = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    } catch (err) {
      throw new Error(`invalid JSON in ${jsonPath}: ${err.message}`);
    }
    for (const field of REQUIRED_MODULE_FIELDS) {
      if (spec[field] === undefined) {
        throw new Error(`${jsonPath}: missing required field "${field}"`);
      }
    }
    modules.push({ ...spec, dir: path.join(modulesDir, entry.name) });
  }
  return modules;
}

/** True when the module's detectFile exists under the target directory. */
export function isModuleDetected(module, targetDir) {
  return fs.existsSync(path.join(targetDir, module.detectFile));
}

// ---------------------------------------------------------------------------
// Workflow body parsing (simple ----delimited frontmatter, flat string keys)
// ---------------------------------------------------------------------------

/**
 * Parses a workflow body file: `---` frontmatter with flat `key: value`
 * string pairs, followed by the markdown body. Hand-rolled on purpose — the
 * format is constrained by DESIGN.md, so no YAML library is needed.
 */
export function parseWorkflowFile(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const lines = raw.split('\n');
  if ((lines[0] ?? '').trim() !== '---') {
    throw new Error(`${filePath}: expected frontmatter opening "---" on line 1`);
  }
  const attrs = {};
  let i = 1;
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '---') break;
    if (line.trim() === '' || line.trim().startsWith('#')) continue;
    const match = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    if (!match) {
      throw new Error(`${filePath}: cannot parse frontmatter line: "${line}"`);
    }
    let value = match[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2)
    ) {
      value = value.slice(1, -1);
    }
    attrs[match[1]] = value;
  }
  if (i >= lines.length) {
    throw new Error(`${filePath}: frontmatter never closed with "---"`);
  }
  const body = lines.slice(i + 1).join('\n').replace(/^\n+/, '');
  return { attrs, body };
}

// ---------------------------------------------------------------------------
// YAML value helpers (ported from OpenSpec's command-generation/yaml.ts)
// ---------------------------------------------------------------------------

/**
 * Escapes a string for safe YAML frontmatter output: double-quotes it when it
 * contains YAML-significant characters, otherwise returns it verbatim.
 */
export function escapeYamlValue(value) {
  const needsQuoting = /[:\n\r#{}[\],&*!|>'"%@`]|^\s|\s$/.test(value);
  if (!needsQuoting) return value;
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
  return `"${escaped}"`;
}

/** Always double-quotes (used for YAML list items we inject into config.yaml). */
export function yamlQuote(value) {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
  return `"${escaped}"`;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ---------------------------------------------------------------------------
// Per-tool file rendering (frontmatter shapes mirror stock OpenSpec adapters)
// ---------------------------------------------------------------------------

/** Claude command: .claude/commands/opsx/<id>.md */
export function renderClaudeCommand(command, body) {
  const tags = (command.tags ?? []).map(escapeYamlValue).join(', ');
  return `---
name: ${escapeYamlValue(command.name)}
description: ${escapeYamlValue(command.description)}
allowed-tools: Bash(openspec:*)
category: Workflow
tags: [${tags}]
---

${GENERATED_BY_LINE}

${body.trimEnd()}
`;
}

/** Cursor command: .cursor/commands/opsx-<id>.md */
export function renderCursorCommand(command, body) {
  return `---
name: /opsx-${command.id}
id: opsx-${command.id}
category: Workflow
description: ${escapeYamlValue(command.description)}
---

${GENERATED_BY_LINE}

${body.trimEnd()}
`;
}

/** Codex prompt: ${CODEX_HOME:-~/.codex}/prompts/opsx-<id>.md (global) */
export function renderCodexPrompt(command, body) {
  return `---
description: ${escapeYamlValue(command.description)}
argument-hint: ${escapeYamlValue(command.argumentHint ?? '')}
---

${GENERATED_BY_LINE}

${body.trimEnd()}
`;
}

/** Skill wrapper: <tool>/skills/openspec-plus-<id>/SKILL.md (same body for all tools). */
export function renderSkill(module, command, body) {
  return `---
name: openspec-plus-${command.id}
description: ${escapeYamlValue(command.description)}
allowed-tools: Bash(openspec:*)
license: MIT
compatibility: Requires the openspec CLI and the openspec-plus ${module.name} module.
metadata:
  author: openspec-plus
  version: "${module.version}"
  generatedBy: "openspec-plus@${OPENSPEC_PLUS_VERSION}"
---

${GENERATED_BY_LINE}

${body.trimEnd()}
`;
}

/** Codex prompts directory — MUST honor CODEX_HOME, defaulting to ~/.codex. */
export function codexPromptsDir() {
  return path.join(process.env.CODEX_HOME || path.join(os.homedir(), '.codex'), 'prompts');
}

// ---------------------------------------------------------------------------
// Scaffold copying
// ---------------------------------------------------------------------------

/**
 * Recursively copies a scaffold tree, never overwriting an existing file.
 * `.gitkeep` files are ordinary files here and are copied too.
 */
export function copyScaffold(writer, srcDir, destDir) {
  if (!fs.existsSync(srcDir)) {
    writer.skip(srcDir, 'scaffold source missing — nothing copied');
    return;
  }
  const entries = fs
    .readdirSync(srcDir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyScaffold(writer, src, dest);
    } else if (entry.isFile()) {
      writer.copyKeepExisting(src, dest);
    }
  }
}

// ---------------------------------------------------------------------------
// openspec/config.yaml marker surgery
// ---------------------------------------------------------------------------

function contextStartMarker(moduleName) {
  return `>>> openspec-plus:${moduleName} >>>`;
}

function contextEndMarker(moduleName) {
  return `<<< openspec-plus:${moduleName} <<<`;
}

function contextManualSnippet(moduleName, snippetLines) {
  return [
    'context: |',
    `  ${contextStartMarker(moduleName)}`,
    ...snippetLines.map((l) => (l ? `  ${l}` : '')),
    `  ${contextEndMarker(moduleName)}`,
  ].join('\n');
}

/**
 * Appends (or replaces, on re-run) the module's context snippet inside the
 * `context: |` block of openspec/config.yaml, wrapped in the literal
 * `>>> openspec-plus:<module> >>>` / `<<< openspec-plus:<module> <<<` marker
 * lines. Creates the file or the `context:` key when absent. Line-based and
 * conservative: an unrecognized structure produces a manual-paste snippet
 * instead of an edit.
 */
export function upsertConfigContext(writer, configPath, moduleName, snippetText) {
  const snippetLines = snippetText.replace(/\s+$/, '').split('\n');
  const blockLines = [contextStartMarker(moduleName), ...snippetLines, contextEndMarker(moduleName)];

  const bail = (why) => {
    writer.manual(
      `Could not safely edit ${configPath} (${why}). Merge this into openspec/config.yaml by hand:`,
      contextManualSnippet(moduleName, snippetLines)
    );
  };

  if (!fs.existsSync(configPath)) {
    const content = ['context: |', ...blockLines.map((l) => (l ? `  ${l}` : ''))].join('\n') + '\n';
    writer.write(configPath, content);
    return;
  }

  const original = fs.readFileSync(configPath, 'utf8');
  const lines = original.split('\n');

  // Re-run: replace an existing marker block in place.
  const startIdx = lines.findIndex((l) => l.trim() === contextStartMarker(moduleName));
  const endIdx = lines.findIndex((l) => l.trim() === contextEndMarker(moduleName));
  if (startIdx !== -1 || endIdx !== -1) {
    if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
      bail('marker lines are unpaired or out of order');
      return;
    }
    const indent = lines[startIdx].match(/^\s*/)[0];
    const replacement = blockLines.map((l) => (l ? indent + l : ''));
    lines.splice(startIdx, endIdx - startIdx + 1, ...replacement);
    const replaced = lines.join('\n');
    writer.write(configPath, replaced.endsWith('\n') ? replaced : replaced + '\n');
    return;
  }

  const ctxIdx = lines.findIndex((l) => /^context:/.test(l));
  if (ctxIdx === -1) {
    // No context key: append a fresh block scalar at the end of the file.
    const out = [...lines];
    while (out.length > 0 && out[out.length - 1].trim() === '') out.pop();
    out.push('context: |', ...blockLines.map((l) => (l ? `  ${l}` : '')));
    writer.write(configPath, out.join('\n') + '\n');
    return;
  }

  // Only a literal block scalar (`context: |`, optionally with chomping /
  // indentation indicators) is recognized; anything else gets the bail-out.
  if (!/^context:\s*\|[0-9+-]*\s*(#.*)?$/.test(lines[ctxIdx])) {
    bail('the context key is not a literal block scalar');
    return;
  }

  // Find the block scalar's extent: subsequent blank or indented lines.
  let blockEnd = ctxIdx + 1;
  let contentIndent = null;
  while (blockEnd < lines.length) {
    const line = lines[blockEnd];
    if (line.trim() === '') {
      blockEnd += 1;
      continue;
    }
    if (/^\s/.test(line)) {
      if (contentIndent === null) contentIndent = line.match(/^\s*/)[0];
      blockEnd += 1;
      continue;
    }
    break;
  }
  const indent = contentIndent ?? '  ';

  // Insert after the last non-blank line of the block.
  let insertAt = blockEnd;
  while (insertAt > ctxIdx + 1 && lines[insertAt - 1].trim() === '') insertAt -= 1;
  lines.splice(insertAt, 0, ...blockLines.map((l) => (l ? indent + l : '')));
  const inserted = lines.join('\n');
  writer.write(configPath, inserted.endsWith('\n') ? inserted : inserted + '\n');
}

function rulesManualSnippet(rules) {
  const out = ['rules:'];
  for (const [artifactId, ruleStrings] of Object.entries(rules)) {
    out.push(`  ${artifactId}:`);
    for (const rule of ruleStrings) out.push(`    - ${yamlQuote(rule)}`);
  }
  return out.join('\n');
}

/**
 * Merges rule strings (from a module's config-snippets/rules.json, shape
 * `{"<artifactId>": ["rule", ...]}`) into the `rules:` mapping of
 * openspec/config.yaml. Every injected rule carries the
 * `[openspec-plus:pillars]` prefix; that prefix is the idempotency check —
 * re-runs replace prefixed items in place. Conservative: unrecognized
 * structure produces a manual-paste snippet.
 */
export function mergeConfigRules(writer, configPath, rules) {
  const bail = (why) => {
    writer.manual(
      `Could not safely edit ${configPath} (${why}). Merge this into openspec/config.yaml by hand:`,
      rulesManualSnippet(rules)
    );
  };

  if (!fs.existsSync(configPath)) {
    writer.write(configPath, rulesManualSnippet(rules) + '\n');
    return;
  }

  const original = fs.readFileSync(configPath, 'utf8');
  const lines = original.split('\n');

  if (lines.some((l) => /^rules:\s*[^#\s]/.test(l))) {
    bail('the rules key has an inline value');
    return;
  }

  let rulesIdx = lines.findIndex((l) => /^rules:\s*(#.*)?$/.test(l));
  if (rulesIdx === -1) {
    while (lines.length > 0 && lines[lines.length - 1].trim() === '') lines.pop();
    lines.push('rules:');
    rulesIdx = lines.length - 1;
  }

  const rulesBlockEnd = () => {
    let end = rulesIdx + 1;
    while (end < lines.length && (lines[end].trim() === '' || /^\s/.test(lines[end]))) end += 1;
    return end;
  };

  for (const [artifactId, ruleStrings] of Object.entries(rules)) {
    const blockEnd = rulesBlockEnd();
    const keyRe = new RegExp(`^(\\s+)${escapeRegExp(artifactId)}:(.*)$`);
    let keyIdx = -1;
    let keyIndent = '';
    for (let i = rulesIdx + 1; i < blockEnd; i++) {
      const match = lines[i].match(keyRe);
      if (match) {
        if (match[2].trim() !== '') {
          bail(`rules.${artifactId} has an inline value`);
          return;
        }
        keyIdx = i;
        keyIndent = match[1];
        break;
      }
    }

    if (keyIdx === -1) {
      // Artifact key absent: append it at the end of the rules block.
      let insertAt = blockEnd;
      while (insertAt > rulesIdx + 1 && lines[insertAt - 1].trim() === '') insertAt -= 1;
      lines.splice(
        insertAt,
        0,
        `  ${artifactId}:`,
        ...ruleStrings.map((rule) => `    - ${yamlQuote(rule)}`)
      );
      continue;
    }

    // Find the artifact's item range (lines indented deeper than the key).
    let itemEnd = keyIdx + 1;
    while (itemEnd < blockEnd) {
      const line = lines[itemEnd];
      if (line.trim() === '') {
        itemEnd += 1;
        continue;
      }
      if (line.match(/^\s*/)[0].length <= keyIndent.length) break;
      itemEnd += 1;
    }

    // Idempotency: remove previously injected (prefixed) single-line items;
    // a prefixed line that is not a simple `- ` item means the user reshaped
    // the entry, so bail rather than mangle it.
    for (let i = itemEnd - 1; i > keyIdx; i--) {
      if (!lines[i].includes(PILLARS_RULE_PREFIX)) continue;
      if (!/^\s*- /.test(lines[i])) {
        bail(`an existing ${PILLARS_RULE_PREFIX} rule under rules.${artifactId} is not a single-line list item`);
        return;
      }
      lines.splice(i, 1);
      itemEnd -= 1;
    }

    let itemIndent = keyIndent + '  ';
    for (let i = keyIdx + 1; i < itemEnd; i++) {
      const match = lines[i].match(/^(\s*)- /);
      if (match) {
        itemIndent = match[1];
        break;
      }
    }

    let insertAt = itemEnd;
    while (insertAt > keyIdx + 1 && lines[insertAt - 1].trim() === '') insertAt -= 1;
    lines.splice(insertAt, 0, ...ruleStrings.map((rule) => `${itemIndent}- ${yamlQuote(rule)}`));
  }

  const text = lines.join('\n');
  writer.write(configPath, text.endsWith('\n') ? text : text + '\n');
}

// ---------------------------------------------------------------------------
// Root AGENTS.md managed block
// ---------------------------------------------------------------------------

/** Composes the managed-block content from the detected module set. */
export function buildAgentsBlock(detectedModules) {
  const lines = [AGENTS_START_MARKER, ''];
  lines.push('## openspec-plus');
  lines.push('');
  const moduleNames = detectedModules.map((m) => `\`${m.name}\``).join(', ');
  lines.push(
    `This repo uses openspec-plus modules (${moduleNames}) — installable customizations ` +
      'layered on OpenSpec through its official customization surfaces. The commands below ' +
      'complement the stock `/opsx:*` workflows. This block is regenerated by ' +
      '`install.mjs`; do not edit between the openspec-plus markers.'
  );
  lines.push('');
  lines.push('| Command | Description |');
  lines.push('|---|---|');
  for (const module of detectedModules) {
    for (const command of module.commands) {
      lines.push(`| \`/opsx:${command.id}\` | ${command.description} |`);
    }
  }

  const names = new Set(detectedModules.map((m) => m.name));
  if (names.has('openspec-pillars')) {
    lines.push('');
    lines.push(
      '**Authority model.** Before planning or authoring artifacts, read ' +
        '`openspec/pillars/DEFINITIONS.md` (vocabulary) first, then `openspec/pillars/README.md` ' +
        '(reading order). Pillars ≻ specs: pillars are timeless beliefs, `openspec/specs/` is ' +
        'current truth — when they disagree, surface the conflict instead of papering over it. ' +
        'Pillar meaning changes are loud and owner-gated: mark the old belief superseded with ' +
        'a pointer, never silently rewrite it.'
    );
  }
  if (names.has('openspec-backlog')) {
    lines.push('');
    lines.push(
      '**Order model.** `openspec/backlog/backlog.md` is the ONLY authority for development ' +
        'order, and each row\'s pointer target IS its status. OpenSpec owns status: ' +
        '`openspec list` shows what is in flight, `openspec/changes/archive/` is what is done — ' +
        'never hand-write "done" in the ledger. Read `openspec/backlog/README.md` before ' +
        'touching the ledger.'
    );
  }

  lines.push('');
  lines.push(AGENTS_END_MARKER);
  return lines.join('\n');
}

/**
 * Regenerates the root AGENTS.md managed block between the openspec-plus
 * markers. Creates AGENTS.md when missing; never touches content outside the
 * markers; appends the block when no markers exist yet.
 */
export function regenerateAgentsBlock(writer, targetDir, detectedModules) {
  const agentsPath = path.join(targetDir, 'AGENTS.md');
  if (detectedModules.length === 0) {
    writer.skip(agentsPath, 'no openspec-plus modules detected — managed block not written');
    return;
  }
  const block = buildAgentsBlock(detectedModules);

  if (!fs.existsSync(agentsPath)) {
    writer.write(agentsPath, block + '\n');
    return;
  }

  const original = fs.readFileSync(agentsPath, 'utf8');
  const lines = original.split('\n');
  const startIdx = lines.findIndex((l) => l.trim() === AGENTS_START_MARKER);
  const endIdx = lines.findIndex((l) => l.trim() === AGENTS_END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx >= startIdx) {
    lines.splice(startIdx, endIdx - startIdx + 1, ...block.split('\n'));
    writer.write(agentsPath, lines.join('\n'));
    return;
  }
  if (startIdx !== -1 || endIdx !== -1) {
    writer.manual(
      `AGENTS.md has unpaired openspec-plus markers — fix them, then re-run, or paste the block by hand:`,
      block
    );
    return;
  }
  writer.write(agentsPath, original.replace(/\s+$/, '') + '\n\n' + block + '\n');
}

// ---------------------------------------------------------------------------
// CLAUDE.md / CODEX.md pointer prepend
// ---------------------------------------------------------------------------

const POINTER_BLOCK = `${POINTER_GUARD}
> Before starting any work, read [AGENTS.md](AGENTS.md) — authority model, planning
> workflow, and repo vocabulary live there.
`;

/**
 * Prepends the AGENTS.md pointer to a root instruction file — only if the
 * file already exists and does not carry the pointer guard yet.
 */
export function prependPointer(writer, filePath) {
  if (!fs.existsSync(filePath)) {
    writer.skip(filePath, 'file does not exist — pointer not added');
    return;
  }
  const original = fs.readFileSync(filePath, 'utf8');
  if (original.includes(POINTER_GUARD)) {
    writer.keep(filePath, 'pointer already present');
    return;
  }
  writer.write(filePath, POINTER_BLOCK + '\n' + original);
}

// ---------------------------------------------------------------------------
// Integration hooks (pairwise registry)
// ---------------------------------------------------------------------------

const DEPTH_LINE = '**Depth:** Minimal | Optimized | Production — <one-sentence boundary>';

const BACKLOG_DEPTH_NOTE = `## Depth column (openspec-pillars integration)

The pillars module is installed, so every ledger table carries a \`Depth\` column after
\`Item\`. Assign each row the smallest truthful depth — \`Minimal | Optimized | Production\`,
as defined in \`openspec/pillars/delivery-depth.md\`. The column is a secondary projection:
the primary anchor is the \`## Depth\` section every change proposal declares, and the two
must agree. Briefs carry a matching \`**Depth:**\` line.`;

const PILLARS_DEPTH_NOTE = `## Backlog projection (openspec-backlog integration)

The backlog module is installed, so the delivery-depth pillar projects into
\`openspec/backlog/\`: the ledger gains a \`Depth\` column and \`templates/brief.md\` a
\`**Depth:**\` line. The proposal's \`## Depth\` section remains the primary anchor; the
ledger column and brief line are secondary projections that must agree with it.`;

function isTableDividerRow(line) {
  return /^\s*\|(\s*:?-+:?\s*\|)+\s*$/.test(line);
}

function insertTableCell(row, cell) {
  const parts = row.split('|');
  parts.splice(2, 0, cell);
  return parts.join('|');
}

/**
 * Inserts a `Depth` column after `Item` in every ledger table whose header
 * starts `| Item |` and lacks a Depth column (header, divider, and a blank
 * cell in existing data rows).
 */
function addLedgerDepthColumn(writer, ledgerPath) {
  if (!fs.existsSync(ledgerPath)) {
    writer.skip(ledgerPath, 'not found — Depth column not inserted (re-run after install)');
    return;
  }
  const lines = fs.readFileSync(ledgerPath, 'utf8').split('\n');
  let changed = false;
  for (let i = 0; i < lines.length; i++) {
    if (!/^\|\s*Item\s*\|/.test(lines[i])) continue;
    if (/\|\s*Depth\s*\|/.test(lines[i])) continue;
    lines[i] = insertTableCell(lines[i], ' Depth ');
    let j = i + 1;
    if (j < lines.length && isTableDividerRow(lines[j])) {
      lines[j] = insertTableCell(lines[j], '---');
      j += 1;
    }
    while (j < lines.length && /^\|/.test(lines[j])) {
      lines[j] = insertTableCell(lines[j], ' ');
      j += 1;
    }
    changed = true;
  }
  if (changed) {
    writer.write(ledgerPath, lines.join('\n'));
  } else {
    writer.keep(ledgerPath, 'Depth column already present');
  }
}

/** Adds the `**Depth:**` line to the brief template, after `**Depends on:**`. */
function addBriefTemplateDepthLine(writer, templatePath) {
  if (!fs.existsSync(templatePath)) {
    writer.skip(templatePath, 'not found — Depth line not inserted (re-run after install)');
    return;
  }
  const text = fs.readFileSync(templatePath, 'utf8');
  if (/^\*\*Depth:\*\*/m.test(text)) {
    writer.keep(templatePath, 'Depth line already present');
    return;
  }
  const lines = text.split('\n');
  const idx = lines.findIndex((l) => l.startsWith('**Depends on:**'));
  if (idx === -1) {
    writer.manual(
      `Could not find the "**Depends on:**" line in ${templatePath}. Add this line after it by hand:`,
      DEPTH_LINE
    );
    return;
  }
  lines.splice(idx + 1, 0, DEPTH_LINE);
  writer.write(templatePath, lines.join('\n'));
}

/** Appends a marker-guarded depth cross-note to a scaffold README. */
function appendDepthNote(writer, readmePath, note) {
  if (!fs.existsSync(readmePath)) {
    writer.skip(readmePath, 'not found — depth cross-note not added (re-run after install)');
    return;
  }
  const text = fs.readFileSync(readmePath, 'utf8');
  if (text.includes(DEPTH_NOTE_GUARD)) {
    writer.keep(readmePath, 'depth cross-note already present');
    return;
  }
  writer.write(readmePath, text.replace(/\s+$/, '') + '\n\n' + DEPTH_NOTE_GUARD + '\n' + note + '\n');
}

/**
 * Pairwise integration hooks. A hook fires when every module in `requires`
 * is detected in the target (whichever module was installed last).
 */
export const integrationHooks = [
  {
    id: 'backlog+pillars',
    requires: ['openspec-backlog', 'openspec-pillars'],
    run({ writer, targetDir }) {
      addLedgerDepthColumn(writer, path.join(targetDir, 'openspec', 'backlog', 'backlog.md'));
      addBriefTemplateDepthLine(
        writer,
        path.join(targetDir, 'openspec', 'backlog', 'templates', 'brief.md')
      );
      appendDepthNote(writer, path.join(targetDir, 'openspec', 'backlog', 'README.md'), BACKLOG_DEPTH_NOTE);
      appendDepthNote(writer, path.join(targetDir, 'openspec', 'pillars', 'README.md'), PILLARS_DEPTH_NOTE);
    },
  },
];

/** Runs every hook whose required modules are all in the detected set. */
export function runIntegrationHooks(writer, targetDir, detectedNames) {
  for (const hook of integrationHooks) {
    if (!hook.requires.every((name) => detectedNames.has(name))) continue;
    console.log(`\nIntegration hook: ${hook.id}`);
    hook.run({ writer, targetDir });
  }
}
